server/edusync/src/main/java/com/codestates/edusync/audit/utils/ErrorResponder.java
server/edusync/src/main/java/com/codestates/edusync/auth/dto/LoginDto.java
server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtAuthenticationFilter.java
server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtVerificationFilter.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAccessDeniedHandler.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAuthenticationEntryPoint.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAuthenticationFailureHandler.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAuthenticationSuccessHandler.java
server/edusync/src/main/java/com/codestates/edusync/auth/jwt/JwtTokenizer.java
server/edusync/src/main/java/com/codestates/edusync/config/SecurityConfiguration.java
server/edusync/src/main/java/com/codestates/edusync/member/controller/MemberController.java
server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberDto.java
server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberJoinResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/member/entity/Member.java
server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java
server/edusync/src/main/java/com/codestates/edusync/response/ErrorResponse.java

JWT 구현을 완료했으며 인증 성공 유무에 따른 전후처리와 예외 처리를 추가했습니다.

feat : JWT 구현 + 인증 예외처리

---

client/src/pages/Profile.tsx

프로필 폴더를 갖고, git 작업 테스트를 한 내용입니다.

feat : 프로필 작업 테스트

---

README.md

README.md 프론트엔드 기술 스택 TS, vite, Recoil 추가했습니다.

docs : README.md 프론트엔드 기술 스택 수정

---

server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtAuthenticationFilter.java
server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtVerificationFilter.java

fix : 토큰헤더 변경

---

server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtAuthenticationFilter.java
server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtVerificationFilter.java
server/edusync/src/main/java/com/codestates/edusync/exception/ExceptionCode.java
server/edusync/src/main/java/com/codestates/edusync/member/controller/MemberController.java
server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberJoinResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/member/entity/Member.java
server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java

feat : 회원 삭제 구현

---

server/edusync/src/main/java/com/codestates/edusync/audit/utils/ErrorResponder.java
server/edusync/src/main/java/com/codestates/edusync/auth/filter/JwtVerificationFilter.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAccessDeniedHandler.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAuthenticationEntryPoint.java
server/edusync/src/main/java/com/codestates/edusync/auth/handler/MemberAuthenticationFailureHandler.java

fix : 잘못된 토큰일 경우 401 반환하도록 수정

---

server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberDto.java
server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberJoinResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/member/entity/Member.java
server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java

fix : location을 클래스메이트로 이동 (member에서 삭제)

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/GlobalStyle.tsx
client/src/env.d.ts
client/src/index.css
client/src/main.tsx
client/src/pages/login.tsx
client/src/pages/signup.tsx
package-lock.json
package.json

- 닉네임, 이메일, 비밀번호 post
- 응답이 500번 인 경우 -> 이메일이 중복되었다는 경고 반환
-  닉네임, 이메일, 비밀번호 중 하나라도 없으면 3가지을 모두 입력하라는 경고 반환
- 회원가입 성공시 로그인 페이지로 이동

[FE] signup 기능

---

server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java
server/edusync/src/main/java/com/codestates/edusync/util/VerifyMember.java

(동일한 기능을 수행하는 메서드 이름 통일을 위해 추가)

feat : member 인터페이스 구현

---

server/edusync/src/main/java/com/codestates/edusync/study/classmate/entity/Classmate.java

엔티티 매핑 이름 수정

---

server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/member/entity/Member.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/dto/SearchTagResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/entity/SearchTag.java
server/edusync/src/main/java/com/codestates/edusync/study/calendarinfo/dto/CalendarInfoSingleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/calendarinfo/entity/CalendarInfo.java
server/edusync/src/main/java/com/codestates/edusync/study/classmate/dto/ClassmateResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/classmate/entity/Classmate.java
server/edusync/src/main/java/com/codestates/edusync/study/locationinfo/entity/LocationInfo.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/classmate/dto/CalendarClassmateResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/studygroup/dto/CalendarStudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/timeschedule/dto/TimeScheduleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/timeschedule/dto/TimeScheduleSingleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/timeschedule/entity/TimeSchedule.java
server/edusync/src/main/java/com/codestates/edusync/study/postcomment/dto/StudyPostCommentResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/dto/StudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/entity/Studygroup.java
server/edusync/src/main/java/com/codestates/edusync/study/studyjoin/dto/StudygroupJoinResponseDto.java

[fix: studygroup Leader 엔티티 매핑 수정](https://github.com/codestates-seb/seb43_main_016/commit/40e280a15d31660246b59a2cfe990ccd0f25da91)
[feat: 맴버 등급 추가 ( grade )](https://github.com/codestates-seb/seb43_main_016/commit/f6a2b51d4f4a033c1ab9b2f1d95f163d1737f682)
[feat: 맴버 응답 DTO 추가](https://github.com/codestates-seb/seb43_main_016/commit/0a41f29c256eb582f0fd5f9f9f1b869dac56ca4c)
[feat: ClassmateResponseDto 구현](https://github.com/codestates-seb/seb43_main_016/commit/b30b60c1061b679efc49740f0bf8e8f0c20412ba)
[feat: StudygroupJoinResponseDto 구현](https://github.com/codestates-seb/seb43_main_016/commit/8587e01aff54c43a995ab785bfed2801a3915053)
[feat: StudygroupResponseDto 구현 - Studygroup 엔티티 필드 추가 ( platform )](https://github.com/codestates-seb/seb43_main_016/commit/2782a60830ee0a734ca450afd04532735 …

Feat be/dto - ResponseDto 추가, 연관 entity 추가 및 수정

---

server/edusync/src/main/java/com/codestates/edusync/infodto/calendarinfo/dto/CalendarInfoDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/calendarinfo/dto/CalendarInfoSingleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/calendarinfo/entity/CalendarInfo.java
server/edusync/src/main/java/com/codestates/edusync/infodto/locationinfo/dto/LocationInfoDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/locationinfo/entity/LocationInfo.java
server/edusync/src/main/java/com/codestates/edusync/infodto/timeschedule/dto/TimeScheduleInfoDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/timeschedule/dto/TimeScheduleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/timeschedule/dto/TimeScheduleSingleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/infodto/timeschedule/entity/TimeSchedule.java
server/edusync/src/main/java/com/codestates/edusync/study/classmate/entity/Classmate.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/classmate/dto/CalendarClassmateResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/classmate/entity/CalendarClassmate.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/studygroup/dto/CalendarStudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/studygroup/entity/CalendarStudygroup.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/dto/StudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/entity/Studygroup.java
server/edusync/src/main/resources/application.yml

[move: Info 폴더 이동 ( CalendarInfo, LocationInfo, TimeSchedule )](https://github.com/codestates-seb/seb43_main_016/commit/ee19394c18b050d83d4b19ab0cc7ad8cb5467836)
[move: CalendarInfo Dto 전용 정보](https://github.com/codestates-seb/seb43_main_016/commit/3fd04baa3d07a4ec031a50ce59d643078c32a053)
[move: TimeScheduleInfo Dto 전용 정보 ( Post, Patch, Response 공용 )](https://github.com/codestates-seb/seb43_main_016/commit/4601a0eb598b5afa7834ac4a7b807cad17210bcc)
[feat: CalendarInfo Dto 전용 정보 ( Post, Patch, Response 공용으로 변경 )](https://github.com/codestates-seb/seb43_main_016/commit/adfc8dd12916703992293f91a563f6b137b18197)
[feat: LocationInfo Dto 전용 정보 ( Post, Patch, Response 공용 )](https://github.com/codestates-seb/seb43_main_016/commit/656f47c74548c6d71629448a742e310adf0b1900)
[fix: …

Be feat/dto - studygroup Post, Patch Dto 추가

---

server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java

fix : 비밀번호 비교 방법 수정

---

server/edusync/src/main/java/com/codestates/edusync/member/controller/MemberController.java
server/edusync/src/main/java/com/codestates/edusync/member/dto/MemberDto.java
server/edusync/src/main/java/com/codestates/edusync/member/service/MemberService.java

fix : 모든 FATCH요청 단일변경 가능하게 수정

---

server/edusync/src/main/java/com/codestates/edusync/searchtag/repository/SearchTagRepository.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/service/SearchTagService.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/repository/StudygroupRepository.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/service/StudygroupService.java

[BE] feat: 스터디 조회 기능 테스트 완료

---

server/edusync/src/main/java/com/codestates/edusync/searchtag/controller/SearchTagController.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/dto/SearchTagDto.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/mapper/SearchTagMapper.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/repository/SearchTagRepository.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/service/SearchTagService.java
server/edusync/src/main/java/com/codestates/edusync/searchtag/utils/SearchTagManager.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/dto/StudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/dto/StudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/mapper/StudygroupMapper.java

[구현] 태그 검색 기능 추가

---

server/edusync/src/main/java/com/codestates/edusync/member/entity/Member.java

Dev 에서 Be 로 Pull 할 때 충돌이 많이 났지만, Be 를 기준으로 업데이트 했습니다.

Main -> Dev -> Be 순으로 브랜치 Pull 하며 Merge 작업 했습니다.

---

client/src/pages/StudyPost.tsx

Fix: build 위한 error 해결

---

client/src/components/GoogleLogin.tsx
client/src/pages/Login.tsx
client/src/pages/SignUp.tsx

구글로그인 링크 추가했습니다. 
추가로 로그인 엔터로 이제 가능합니다! ㅎㅎ

[FE]add: 구글로그인 링크

---

server/edusync/src/main/java/com/codestates/edusync/globalutils/StudygroupVerifiable.java
server/edusync/src/main/java/com/codestates/edusync/globalutils/VerifyStudygroupUtils.java
server/edusync/src/main/java/com/codestates/edusync/study/plancalendar/studygroup/service/CalendarStudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/study/postcomment/service/StudygroupPostCommentService.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/mapper/StudygroupMapper.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/service/StudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroup/utils/StudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroupjoin/controller/StudygroupJoinController.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroupjoin/repository/StudygroupJoinRepository.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroupjoin/service/StudygroupJoinService.java
server/edusync/src/main/java/com/codestates/edusync/study/studygroupjoin/utils/StudygroupJoinManager.java

fix: StudygroupService interface
fix: StudygroupJoinService interface

[BE] 스터디 그룹 인터페이스 적용

---

server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/controller/CalendarStudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarStudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarStudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/controller/StudygroupPostCommentController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/service/StudygroupPostCommentManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/service/StudygroupPostCommentService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/controller/StudygroupJoinController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinService.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/controller/SearchTagController.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/service/SearchTagManager.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/service/SearchTagService.java

- 메서드 명이 패키지 명과 중복되는 사항 수정
- #175 
<br>
- 코드의 동작을 설명하는 메서드명은 남겨뒀습니다
<br>
- #174 
<br>
- #177

[리펙터링] 메서드 이름 중복 제거

---

server/edusync/build.gradle
server/edusync/src/main/resources/application.yml
server/edusync/src/main/resources/db/migration/V1.0__init.sql

[구현] feat: flyway 적용

---

server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/mapper/StudygroupMapper.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java

[구현] fix: 스터디 모집상태 수정, 리턴값 수정

---

.github/workflows/gradle.yml
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupDto.java

[구현] 스터디 그룹 요일 포맷 수정

---

server/edusync/src/main/java/com/codestates/edusync/model/common/dto/DateRangeDto.java
server/edusync/src/main/java/com/codestates/edusync/model/common/dto/TimeRangeDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/entity/Studygroup.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/mapper/StudygroupMapper.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java

- #205
- 스터디 모집글
1. 스터디 모집글 등록
2. 스터디 모집글 수정
3. 스터디 모집글 모집 상태 관리
4. 스터디 모집글 조회
5. 스터디 모집글 리스트 조회

[구현] 스터디 모집 기능 #205

---

server/edusync/src/main/java/com/codestates/edusync/EdusyncApplication.java
server/edusync/src/main/java/com/codestates/edusync/model/common/entity/Auditable.java
server/edusync/src/main/resources/application.yml
server/edusync/src/main/resources/db/migration/V1.2__fix_time_schedule.sql

- #205
- #213
영향
- 스터디 모집 삭제 기능 NPE 발생 처리

[BE] time_schedule 컬럼 네임 수정

---

server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/mapper/StudygroupMapper.java
server/edusync/src/main/resources/db/migration/V1.3__add_studygroup_join.sql

스터디 가입 신청 시 예외발생(NPE) - #218
- studygroup_join 테이블 컬럼 추가 
: created_at
: modified_at
[skip ci]

[BE] 스터디 가입 신청 시 예외 - DB스키마 수정 완료

---

client/src/App.tsx
client/src/apis/StudyGroupApi.ts
client/src/pages/ProfileStudyList.tsx

* 토큰 요청 리팩토링
* 리팩토링 수정 완료
* 병합 전 커밋
* 마이페이지 구현 및 테스트 완료
* 마이페이지 구현 완료 및 리스트 오류 해결 중
* 멤버 목록 조회
* 가입된 멤버조회 구현

2차 세부사양 테스트 최종본 (#243)

---

server/edusync/src/main/java/com/codestates/edusync/exception/ExceptionCode.java
server/edusync/src/main/java/com/codestates/edusync/handler/OAuth2MemberSuccessHandler.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/MemberUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/TagFormatConverter.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/CommonStudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/dto/StudygroupResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/mapper/StudygroupMapper.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/controller/SearchTagController.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/dto/SearchTagDto.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/dto/SearchTagResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/studyaddons/searchtag/mapper/SearchTagMapper.java

- ##254 
- Tag 조회 시 마지막 값 하나만 조회하는 버그 수정
<br>

[구현] 스터디그룹 없이 태그 등록하는 엔드포인트 추가 (테스트용) 

---

client/src/App.tsx
client/src/apis/CommentApi.ts
client/src/apis/StudyGroupApi.ts
client/src/apis/TokenRequestApi.ts
client/src/components/StudyComment.tsx
client/src/components/StudyCommentList.tsx
client/src/components/TagInput.tsx
client/src/pages/HTestPage.tsx
client/src/pages/StudyPost.tsx

- /haeun 임시 페이지에서 확인 가능 (스터디컨텐츠 페이지 구현 후 삭제 예정)
- 본인만 삭제, 수정가능: 에러형식으로 경고 -> "본인의 댓글만 삭제 가능합니다." alert 추가 예정
- 변경사항 바로 업데이트 수정 예정 (지금은 새로고침 해야 변경사항 볼 수 있음)

[구현] 댓글 (comment) CRUD  구현 완료

---

server/edusync/src/main/java/com/codestates/edusync/exception/ExceptionCode.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/controller/StudygroupPostCommentController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/dto/StudygroupPostCommentResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/mapper/StudygroupPostCommentMapper.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/entity/Studygroup.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/entity/StudygroupJoin.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/repository/StudygroupJoinRepository.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinService.java

[변경] 스터디 캘린더 자동 등록 기능

---

server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarMemberService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarStudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CommonCalendarFeature.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/entity/StudygroupJoin.java

[자잘한 것 수정]

---

client/src/App.tsx
client/src/apis/CommentApi.ts
client/src/pages/ProfileStudyList.tsx
client/src/pages/StudyContent.tsx
client/src/pages/StudyList.tsx
client/src/pages/StudyPost.tsx

StudyContent 페이지 모집글 내용 조회, 삭제, 모집중/완료 상태 표시 일단 구현했고 삭제 버튼도 본인이 쓴 글만 정상 작동합니다!

Feat: 스터디 모집글 내용 조회, 삭제 1차 완성, 스터디 모집글 작성 예외처리 시작

---

client/src/components/TagDropdown.tsx
client/src/pages/Login.tsx
client/src/pages/SignUp.tsx

fix: 태그 mapping err & 탈퇴회원 로그인 관리

fix: 태그 mapping err & 탈퇴회원 로그인 관리

---

client/src/pages/Home.tsx

feat: 홈 화면 시작

---

client/src/App.tsx
client/src/apis/StudyGroupApi.ts
client/src/components/StudyListTag.tsx
client/src/pages/StudyContent.tsx
client/src/pages/StudyUpdate.tsx

feat: content수정기능 구현 (시간 부분 미구현)

feat: content수정기능 구현 (시간 부분 미구현)

---

client/src/components/modal/MemberRestoreModal.tsx
client/src/pages/Login.tsx
client/src/pages/ProfileInfo.tsx
client/src/pages/SignUp.tsx

탈퇴회원 복구 모달 만들었습니다. (기능 정상 작동 확인)

[Feat]탈퇴회원 복구 기능

---

.vscode/extensions.json
client/src/components/ListFilter.tsx
client/src/components/WaitingList.tsx
client/src/components/gnb/GNB.tsx
client/src/components/studyManage/CandidateManage.tsx
client/src/components/studyManage/MemberManage.tsx
client/src/pages/Profile.tsx
client/src/pages/ProfileCalendar.tsx
client/src/pages/ProfileInfo.tsx
client/src/pages/ProfileStudyList.tsx
client/src/pages/ProfileStudyManage.tsx
client/src/pages/StudyContent.tsx
client/src/pages/StudyList.tsx
client/src/pages/StudyPost.tsx
client/src/pages/StudyUpdate.tsx

Feat: GNB 메뉴 버튼 추가, 리스트 filter select 수정

Feat: GNB 메뉴 버튼 추가, 스터디 관리 페이지 디자인 완성

---

client/src/components/modal/LoginAlertModal.tsx
client/src/pages/StudyContent.tsx

로그인이 필요합니다 모달 생성(스터디 컨텐츠 누르면 로그인 이동 할때 모달 오픈)

로그인이 필요합니다 모달 생성

---

client/src/components/TagDropdown.tsx
client/src/components/TagInput.tsx
client/src/components/gnb/GNB.tsx
client/src/pages/StudyPost.tsx
client/src/pages/StudyUpdate.tsx

스터디 작성 기본값, 태그 CSS 등

---

client/src/pages/StudyList.tsx

design: 스터디리스트 카드 디자인 수정

---

server/edusync/src/main/java/com/codestates/edusync/exception/ExceptionCode.java
server/edusync/src/main/java/com/codestates/edusync/model/common/dto/TimeRangeDto.java
server/edusync/src/main/java/com/codestates/edusync/model/member/service/MemberService.java
server/edusync/src/main/java/com/codestates/edusync/model/member/utils/NickNameValidationUtility.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/controller/CalendarMemberController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/dto/CalendarMemberResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/dto/CalendarStudygroupDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/dto/TimeScheduleSingleResponseDto.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarMemberService.java

[수정] 개인 스케쥴 등록 시 not null 유효성 검사

---

server/edusync/src/main/java/com/codestates/edusync/config/SecurityConfiguration.java
server/edusync/src/main/java/com/codestates/edusync/exception/ExceptionCode.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/MemberUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/VerifyCalendarUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/VerifyStudygroupPostCommentUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/VerifyStudygroupUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/common/utils/VerifyTimeScheduleUtils.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/controller/CalendarMemberController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/controller/CalendarStudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarMemberService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarStudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/plancalendar/service/CalendarStudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/controller/StudygroupPostCommentController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/mapper/StudygroupPostCommentMapper.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/service/StudygroupPostCommentManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/postcomment/service/StudygroupPostCommentService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/controller/StudygroupController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroup/service/StudygroupService.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/controller/StudygroupJoinController.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinManager.java
server/edusync/src/main/java/com/codestates/edusync/model/study/studygroupjoin/service/StudygroupJoinService.java

- #350 
<br>
- 스터디 캘린더
- 개인 캘린더
- 스터디 댓글
- 스터디 그룹
- 스터디 가입신청
<br>

[수정] NPE 500 -> 400 예외처리

---

client/src/pages/StudyList.tsx

design: 스터디 리스트 css 수정
